version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/snowe/
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
    - location: scripts/health_check.sh
      runas: ubuntu
    - location: scripts/switch.sh
      runas: ubuntu
    - location: scripts/delete.sh
      runas: ubuntu